shop/authentication/urls.py
from django.urls import path
from .views import UserCreationView, UserProfileView, LoginView, LogoutView

urlpatterns = [
    path('register/', UserCreationView.as_view(), name='register'),
    path('<int:pk>/profile/', UserProfileView.as_view(), name='profile'),
    path('login/', LoginView.as_view(), name="login"),
    path('logout/', LogoutView.as_view(), name="logout"),
]

shop/devices/urls.py
from django.urls import path
from .views import (
    DevicesListView,
    DevicesTypeListView,
    DevicesDetailView,
    DeviceDeleteView,
    DeviceCreateView,
    SliderListView,
)
app_name = 'devices'

urlpatterns = [
    path('', SliderListView.as_view(), name='slider'),
    path('product_list/', DevicesListView.as_view(), name='devices-list'),
    path('create/', DeviceCreateView.as_view(), name='create'),
    path('<int:pk>/', DevicesDetailView.as_view(), name='details'),
    path('<str:type_name>/', DevicesTypeListView.as_view(), name='type-list'),
    path('<int:pk>/delete/', DeviceDeleteView.as_view(), name='delete'),
]

shop/shop/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include('devices.urls')),
    path('accounts/', include('authentication.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns.append(
        path('__debug__/', include('debug_toolbar.urls'))
    )

shop/authentication/models.py
from django.contrib.auth.models import AbstractUser
from django.contrib.auth import get_user_model
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver

UserModel: AbstractUser = get_user_model()


class UserProfile(models.Model):
    user = models.OneToOneField(
        UserModel,
        primary_key=True,
        on_delete=models.CASCADE,
    )
    city = models.CharField(max_length=64, null=False, blank=True)

    def __str__(self):
        return self.user.username


@receiver(post_save, sender=UserModel)
def user_saved_handler(instance: UserModel, created: bool, **kwargs):
    if not created:
        return

    UserProfile.objects.create(user=instance)

shop/devices/models.py
from django.db import models
from authentication.models import UserModel


class DevicesType(models.Model):
    class Meta:
        verbose_name_plural = "Devices Type"
    name = models.CharField(max_length=20)

    def __str__(self):
        return self.name


class Devices(models.Model):
    class Meta:
        verbose_name_plural = "Devices"

    company = models.CharField(max_length=64)
    model = models.CharField(max_length=64)
    price = models.FloatField(null=True)
    description = models.TextField(blank=True, null=False)
    type = models.ForeignKey(DevicesType, on_delete=models.PROTECT, null=True)
    image = models.ImageField(upload_to='images/', null=True, blank=True)

    def __str__(self):
        return self.company

    def __repr__(self):
        return f"<Device #{self.pk} {self.company!r}>"


class Slider(models.Model):
    image = models.ImageField(upload_to='images/slider')
    title = models.CharField(max_length=150)
    sub_title = models.CharField(max_length=100)

    def __str__(self):
        return self.title

shop/authentication/forms.py
from django.contrib.auth.forms import UserCreationForm as CreationForm
from django.contrib.auth.forms import ValidationError
from .models import UserModel, UserProfile
from django.contrib.auth.forms import AuthenticationForm


class UserCreationForm(CreationForm):
    class Meta:
        model = UserModel
        fields = ("username", "email", "password1", "password2")


class UserLoginForm(AuthenticationForm):
    class Meta:
        model = UserModel
        fields = ("username", "password")

shop/devices/forms.py
from django.forms import ModelForm
from .models import Devices


class DeviceCreateForm(ModelForm):

    class Meta:
        model = Devices
        fields = "company", "model", "price", "description", "type", "image"

shop/authentication/views.py
from .forms import UserCreationForm, UserLoginForm
from .models import UserProfile, UserModel
from django.views.generic import CreateView, DetailView
from django.urls import reverse_lazy
from django.contrib.auth.views import LoginView as LoginClass
from django.contrib.auth.views import LogoutView as LogoutClass


class UserProfileView(DetailView):
    queryset = UserProfile.objects.select_related('user')
    context_object_name = "profile"
    template_name = "registration/profile.html"


class UserCreationView(CreateView):
    model = UserModel
    success_url = reverse_lazy("devices:devices-list")
    form_class = UserCreationForm
    template_name = "registration/create.html"


class LoginView(LoginClass):
    next_page = reverse_lazy("devices:devices-list")
    form_class = UserLoginForm


class LogoutView(LogoutClass):
    next_page = reverse_lazy("devices:devices-list")

shop/devices/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from .forms import DeviceCreateForm
from .models import Devices, DevicesType, Slider
from django.views.generic import ListView, DetailView, DeleteView, CreateView
from django.urls import reverse_lazy, reverse


class SliderListView(ListView):
    queryset = Slider.objects.all()
    context_object_name = 'slider'
    template_name = 'devices/preview.html'


class DevicesListView(ListView):
    queryset = Devices.objects.select_related('type')
    template_name = 'devices/index.html'
    context_object_name = "devices"


class DevicesTypeListView(ListView):
    queryset = Devices.objects.select_related("type")
    context_object_name = "devices"

    def get_queryset(self):
        qs = super().get_queryset()
        type: DevicesType = get_object_or_404(
            DevicesType, name=self.kwargs["type_name"]
        )

        return qs.filter(type__name=type.name)


class DevicesDetailView(DetailView):
    queryset = Devices.objects.select_related('type')
    context_object_name = "device"
    template_name = "devices/details.html"


class DeviceDeleteView(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    model = Devices
    success_url = reverse_lazy("devices:devices-list")
    permission_required = (
        "delete_devices",
        "delete_laptop",
        "delete_phone",
        "delete_tablet",
    )


class DeviceCreateView(LoginRequiredMixin, PermissionRequiredMixin,CreateView):
    model = Devices
    form_class = DeviceCreateForm
    permission_required = (
        "create_devices",
        "create_laptop",
        "create_phone",
        "create_tablet",
    )

    def get_success_url(self):
        return reverse("devices:details", kwargs={"pk": self.object.pk})

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.save()
        return super().form_valid(form)

shop/devices/templates/base.html
<!doctype html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title>
            {% block title %}
                Base Title
            {% endblock %}
        </title>
        {% load static %}
        <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
        <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
        <style>
            body{
                background: #ffffff;
            }
            nav {
                background: rgba(0,0,0,0.8);
            }
        </style>
        {% block head %}
        {%  endblock %}
    </head>
    <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light shadow p-3 mb-5 bg-white rounded">
        <a class="navbar-brand m-lg-2" href="{% url 'devices:devices-list' %}">Navigation</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'devices:type-list' type_name='Laptop' %}">Laptops</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'devices:type-list' type_name='Phone'%}">Phones</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'devices:type-list' type_name='Tablet' %}">Tablets</a>
                </li>
            </ul>
        </div>
        {% if user.is_authenticated %}
            <ul class="navbar-nav p-lg-2">
            <li  class="nav-item ">
                <a class="nav-link mr-sm-2" href="{% url 'profile' pk=user.id %}">Hello {{ user.username }} !</a>
            <li  class="nav-item ">
                <a class="nav-link mr-sm-2" href="{% url 'logout'%}"> Logout </a>
            </ul>
        {% else %}
            <ul class="navbar-nav p-lg-2">
                <li  class="nav-item ">
                    <a class="nav-link mr-sm-2" href="{% url 'login'%}">Login</a>
                </li>
                <li  class="nav-item">
                    <a class="nav-link mr-sm-0" href="{% url 'register'%}">Register</a>
                </li>
            </ul>
        {% endif %}
    </nav>
    {% block body %}
    {% endblock %}
</body>
</html>

shop/devices/templates/devices/details.html
{% extends 'base.html' %}

{% block title %}
    Device Page
{% endblock %}

{% block body %}
    <div class="shop-detail-box-main">
    <div class="container">
        <div class="row">
            <div class="col-xl-7 col-lg-7 col-md-6">
                <div> <img class="d-block w-100" src="{{device.image.url}}" alt="First slide"> </div>
            </div>
            <div class="col-xl-5 col-lg-5 col-md-6">
                <div class="single-product-details">
                    <h2 class="text-justify">{{device.company}}</h2>
                    <h5> Model: {{device.model}} </h5>
                    <h2> Price: {{device.price}} $ </h2>
                    <div class="price-box-bar mt-4">
                        <div class="cart-and-bay-btn">
                            {% if user.is_authenticated %}
                                <button href="#" class="btn btn-primary"
                                    style="border-radius: 25px; height: 50px; width: 120px;">Add to cart</button>
                            {% else %}
                                <a href="{% url 'login' %}" class="btn btn-primary"
                                    style="border-radius: 25px; height: 50px; width: 120px;"><p style="margin-top: 5px">Add to cart</p></a>
                            {% endif %}
                            {% if user.is_superuser %}
                                <a href="{% url 'devices:delete' pk=device.id %}" class="btn btn-danger"
                                    style="border-radius: 25px; height: 50px; width: 120px"><p style="margin-top: 5px">Delete</p></a>
                            {% endif %}

                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="row my-5">
            <div class="col-xl-12 col-lg-12 col-md-12">
                <div class="title-left">
                    <h2 class="font-weight-bold">Product Description</h2>
                </div>
                    <p><i class="fas fa-angle-right"></i><i class="fas fa-angle-right"></i> {{device.description}}</p>
            </div>
        </div>
    </div>
</div>

{% endblock %}

shop/devices/templates/devices/devices_confirm_delete.html
{% extends 'base.html' %}

{% block title %}
    Delete #{{ object.pk }}
{% endblock %}
{%  block body %}
    <div class="text-center">
        <h2> Are you sure to delete this device?</h2>
        {% if object.image.url is not null  %}
        <img src="{{ object.image.url }}" alt="">
        {% else %}
            <br>
            <h3> No Photo</h3>
        {% endif %}
        <form method="post">{% csrf_token %}
            {{ form }}
            <div>
                <button type="submit" class="btn btn-primary">Delete</button>
                <a class="btn btn-danger" href="{% url 'devices:devices-list'%}" role="button">Go back</a>
            </div>
        </form>
    </div>


{% endblock %}

shop/devices/templates/devices/devices_form.html
{% extends 'base.html' %}
{% block body %}
    <form method="post" class="mt-auto">
    {% csrf_token %}
        {% for attr in form %}
            <div class="text-center">
                <h4> {{ attr.label }} </h4>
                {{ attr }}
            </div>
        {% endfor %}
    <div class="text-center">
        <button type="submit" class="btn btn-primary">Create</button>

    </div>

  </form>

{% endblock %}

shop/devices/templates/devices/devices_list.html
{% extends 'base.html' %}

{% block title %}
    {% with devices|first as first_device %}
            {{ first_device.type }}
        {% endwith %}
    Page
{% endblock %}

{% block body %}
    {% if user.is_superuser %}
        <div class="text-center" style="width: 100%; height: 50px">
                <a href="{% url 'devices:create' %}" class="btn btn-primary"
                        style="border-radius: 18px; height: 40px; width: 280px;">Add Device To list</a>
        </div>
    {% endif %}
    <div class="shop-box-inner" style="margin-top: 15px">
    <div class="container">
        <div class="row">
            <div class="col-xl-12 col-lg-12 col-sm-12 col-xs-12">
                <div class="row product-categorie-box">
                    <div class="tab-content">
                        <div role="tabpanel" class="tab-pane fade show active" id="grid-view">
                            <div class="row">
                                {% for device in devices %}
                                <div class="col-lg-3 col-md-6 special-grid "
                                     style="margin-bottom: 40px; height: 410px;">
                                    <div class="products-single fix shadow p-3 mb-5 bg-white rounded"
                                         style="background-color: #eee; padding-bottom: 10px">
                                        <a href="{% url 'devices:details' pk=device.id%}">
                                        <div class="box-img-hover ctr" style="height:305px; ">
                                            <img src="{{device.image.url}}" class="img-fluid" alt="Image">
                                        </div></a>
                                        <div class="text-center" style="height:105px;">
                                            <div class="text-center">
                                                <h6>{{device.model}}</h6>
                                                <h6>{{device.price}} $</h6>
                                                <button href="#" class="btn btn-primary"
                                                            style="border-radius: 18px; height: 40px; width: 280px;">Add to cart</button>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                {% endfor %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>



{% endblock %}

shop/devices/templates/devices/index.html
{% extends 'base.html' %}
{% block title %}
    Device Page
{% endblock %}
{% block body %}
    {% if user.is_superuser %}
        <div class="text-center" style="width: 100%; height: 50px">
                <a href="{% url 'devices:create' %}" class="btn btn-primary"
                        style="border-radius: 18px; height: 40px; width: 280px; margin-bottom: 15px">Add Device To list</a>
        </div>
    {% endif %}
    <div class="shop-box-inner" style="margin-top: 15px">
    <div class="container">
        <div class="row">
            <div class="col-xl-12 col-lg-12 col-sm-12 col-xs-12">
                <div class="row product-categorie-box">
                    <div class="tab-content">
                        <div role="tabpanel" class="tab-pane fade show active" id="grid-view">
                            <div class="row">
                                {% for device in devices %}
                                <div class="col-lg-3 col-md-6 special-grid "
                                     style="margin-bottom: 40px; height: 410px;">
                                    <div class="products-single fix shadow p-3 mb-5 bg-white rounded"
                                         style="background-color: #eee; padding-bottom: 10px">
                                        <a href="{% url 'devices:details' pk=device.id%}">
                                        <div class="box-img-hover ctr" style="height:305px; ">
                                            <img src="{{device.image.url}}" class="img-fluid" alt="Image">
                                        </div></a>
                                        <div class="text-center" style="height:105px;">
                                            <div class="text-center">
                                                <h6>{{device.model}}</h6>
                                                <h6>{{device.price}} $</h6>
                                                <button href="#" class="btn btn-primary"
                                                            style="border-radius: 18px; height: 40px; width: 280px;">Add to cart</button>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                {% endfor %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

shop/devices/templates/devices/preview.html
{% extends 'base.html' %}
{% block head  %}
{% endblock %}
{% block body %}
    {% load static %}
    <div id="carouselExampleCaptions" class="carousel slide" data-bs-ride="carousel" style="margin-top: 4%">
        <div class="carousel-indicators">
         <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="0" class="active"
            aria-current="true" aria-label="Slide 1" style="background-color: #0a53be"></button>
            <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="1"
            aria-label="Slide 2" style="background-color: #0a53be"></button>
            <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="2"
            aria-label="Slide 3" style="background-color: #0a53be"></button>
        </div>
        <div class="carousel-inner">
        {% for object in slider%}
            <div class="carousel-item {% if forloop.counter0 == 0 %}active{% endif %}" >
                <img src="{{object.image.url}}" style="height: 650px" class="testi-overly d-block w-100" alt="sliderImg">
                <div class="carousel-caption d-none d-md-block">
                <h1 class="animate__animated
                {% if forloop.counter0 == 0 %}
                animate__fadeInDown
                {% endif %}
                {% if forloop.revcounter == 1 %}
                animate__bounce
                {% endif %}
                {% if forloop.revcounter == 2 %}
                animate__fadeInRight
                {% endif %}" style="margin-bottom: 36%; color: black">{{object.title}}</h1>
                {% if user.is_authenticated %}
                    <a class="btn btn-primary" href="{% url 'devices:devices-list'%}" role="button"
                       style="border-radius: 40px; height: 50px; width: 150px;">
                        <p style="margin-top: 6px">Go shop</p>
                    </a>
                {%  else %}
                    <a class="btn btn-primary" href="{% url 'login'%}" role="button"
                       style="border-radius: 40px; height: 50px; width: 150px;">
                        <p style="margin-top: 6px">Go shop</p>
                    </a>
                {% endif %}
                </div>
            </div>
        {% endfor %}
        </div>
    </div>
{% endblock %}